### PR TITLE
[14.0][MIG] account_asset_product_item

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

Depends on:

- [x] ~~https://github.com/nuobit/odoo-addons/pull/58~~

### CODE REVIEW

**Review by ChrisOForgeFlow — APPROVED** [review]
Functional and Code Review

**Review by eantones — CHANGES_REQUESTED** [review]
@ChrisOForgeFlow please squash new commits into the one with title "Migration 14.0"

**Comment by ChrisOForgeFlow** [comment]
> @ChrisOForgeFlow please squash new commits into the one with title "Migration 14.0"

Done

**Review by ChrisOForgeFlow — APPROVED** [review]
Code Review Ok
Functional Review related on #123

**Comment by eantones** [comment]
The functionality of this module is already covered by the new OCA asset module (it's based on it actually), so it was not necessary to migrate it...

**Comment by eantones** [comment]
This functionality was only for the old Odoo asset module which did not create multiple assets when the invoice quantity was greater than one. The new new OCA asset management module already supports this so this module should not be necessary anymore.
@MiquelRForgeFlow @LoisRForgeFlow

**Pull request closed without merging**
