### PR TITLE
[14.0][MIG] sale_order_cancel_stock

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@eantones this one is ready

**Comment by ChrisOForgeFlow** [comment]
@eantones I tried to understand this module, please give some feedback about my revision

- Add on cancel context from_order key to change cancel of picking, from sale orders
- Search every stock.move.line with state done
- Iterate over moves, create key used after to check on origin and destination location
- Accumulate values, if sum is zero you remove key from dictionary qty_balances, but here is my doubt:
> - Only if in the pickings you have moves that cancel each other out, for example 1 move with product a from location A to B, and another move with same product from location B to A with the same quantity on done state, and only in this cases you keep values on qty_balances dict, and return super call
- If last point is not satisfied, find every move with state different of "done" and call cancel action, then write "is_locked" field as True, keeping state on picking

This would mean that all the cancellation of sales orders, it would not change the status of the pickings, they would only place the status is_locked, this is right?

**Comment by ChrisOForgeFlow** [comment]
@eantones this module doesn't should migrated, Because this

https://github.com/odoo/odoo/blob/1d151a8ed51ee10475ee8537199c036341a93022/addons/sale_stock/models/sale_order.py#L216

Because this, only not done pickings is cancel from sale.order

**Comment by eantones** [comment]
> @eantones this module doesn't should migrated, Because this
> 
> https://github.com/odoo/odoo/blob/1d151a8ed51ee10475ee8537199c036341a93022/addons/sale_stock/models/sale_order.py#L216
> 
> Because this, only not done pickings is cancel from sale.order

I see... There are no hooks... So if we want to keep this functionality, we either try to use the context somehow or, if it's not possible then, as a last resort, we should override the whole method.

**Comment by MiquelRForgeFlow** [comment]
@ChrisOForgeFlow @eantones now it keeps same functionality :)

**Pull request merged**
