### PR TITLE
12.0 mig account invoice tax analytic account

### PR DESCRIPTION
**Pull request by VrajaTechnologies**

### CODE REVIEW

**Comment by eantones** [comment]
@VrajaTechnologies Please, squash the "Migration to 12.0" commits into one and "black, isort, prettier" commits into another, and force push it again. It should only be 4 commits in total. Thanks

**Comment by eantones** [comment]
Hi @VrajaTechnologies Travis is ok here, there's something wrong with the order of the commits, the "black, isort, prettier" commit should only have been committed once just before starting to migrate the module, it can never be after the "Migration to 12.0" commit. Please fix it and we can talk about it on the call.

**Comment by eantones** [comment]
@VrajaTechnologies I've been testing this module and It's not working, the "base" should appear on the non deductible tax, now it shows 0
image

**Comment by VrajaTechnologies** [comment]
Hello
can you please write down the step to generate this issue..so we will check
it ..how it added the analytical tax line..
Thanks


Best Regards,

Vraja Technologies

Vraja Technologies
*Odoo ERP Consultancy Service Provider*
207, Time Square, Ayodhya Chowk, • 150 feet ring road, Rajkot - 360006
*India*.
*Skype* :  *live:vrajatechnologies*
[image: email-icon]  ***@***.***
***@***.***>*
[image: website-icon]  *www.vrajatechnologies.com
<https://www.vrajatechnologies.com/>*

**Comment by eantones** [comment]
@VrajaTechnologies I close this PR, I just fixed this on #10

**Pull request closed without merging**
