### PR TITLE
[14.0][MIG] product_unique_barcode

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@eantones this one is ready

**Review by ChrisOForgeFlow — APPROVED** [review]
Functional Review Ok
Code Review, I think that init hook don't execute, because field barcode has sql unique constraint on base code

**Comment by eantones** [comment]
> Functional Review Ok Code Review, I think that init hook don't execute, because field barcode has sql unique constraint on base code

The hook should execute, its only purpose is to check for duplicated barcode before installing the module. If the hook finds a duplicate barcode the user is informed and the module is not installed. Only after the user fixes the duplicates the module can be installed.

**Comment by ChrisOForgeFlow** [comment]
> > Functional Review Ok Code Review, I think that init hook don't execute, because field barcode has sql unique constraint on base code
> 
> The hook should execute, its only purpose is to check for duplicated barcode before installing the module. If the hook finds a duplicate barcode the user is informed and the module is not installed. Only after the user fixes the duplicates the module can be installed.

Ok, then code review is fine too

**Comment by eantones** [comment]
Awesome! I'll merge it then, thanks :-)

**Pull request merged**
