### PR TITLE
[14.0][MIG] account_invoice_tax_analytic_account

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
I somehow I finally accomplished this migration :)

### CODE REVIEW

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Please, test the modules functionally:

1. Migration scripts did not work.
2. Bad initial inheritance of _preprocess_taxes_map. (now fixed and, does it even work?)
3. TypeError: _get_tax_grouping_key_from_tax_line() takes 2 positional arguments but 3 were given...

Test things... at least before adding them to odoo-pre.

**Comment by MiquelRForgeFlow** [comment]
All your detected error have been solved. But I will functionally check in detail if still exists any other stupid error.

**Comment by LoisRForgeFlow** [comment]
After dicussing this module is not need in v14, it can be done out-of-the-box. The PR can be closed.

**Comment by MiquelRForgeFlow** [comment]
Ok, then is not needed.

**Pull request closed without merging**
