### PR TITLE
[14.0][MIG] account_asset_hook

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

`account_asset_management` dependency added in https://github.com/nuobit/odoo-addons/pull/56.

### CODE REVIEW

**Review by ChrisOForgeFlow — APPROVED** [review]
Code Review Ok, this is a technical tool only

**Review by eantones — CHANGES_REQUESTED** [review]
@ChrisOForgeFlow please remove the last commit or squash it into the one with title "Migration 14.0"

**Comment by ChrisOForgeFlow** [comment]
> @ChrisOForgeFlow please remove the last commit or squash it into the one with title "Migration 14.0"

Done

**Comment by LoisRForgeFlow** [comment]
Dependency to account-financial-tools needs to be added in the oca_dependencies.txt.

**Comment by ChrisOForgeFlow** [comment]
> Dependency to account-financial-tools needs to be added in the oca_dependencies.txt.

Rebase works

**Comment by MiquelRForgeFlow** [comment]
@eantones this PR should be merged ASAP. Travis CI in branch 14.0 is broken due to this.

Selection_145

**Review by mariadforgeflow — APPROVED** [review]

**Comment by ChrisOForgeFlow** [comment]
This module should be depreciated, I work on remove dependency from this modules:

#59 
#61

**Comment by MiquelRForgeFlow** [comment]
Depreciated.

**Comment by eantones** [comment]
@MiquelRForgeFlow I see you've copied the method _prepare_asset_values of this module to oca asset module.

**Comment by MiquelRForgeFlow** [comment]
Yeah, it was long ago in https://github.com/OCA/account-financial-tools/pull/1239.

**Pull request closed without merging**
