### PR TITLE
[14.0][MIG] stock_picking_report_delivery_note

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

Depends on:

- [x] https://github.com/nuobit/odoo-addons/pull/36.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@eantones this one is ready

**Comment by MiquelRForgeFlow** [comment]
The scss and templates of the report have to be adjusted.

**Review by mariadforgeflow — APPROVED** [review]
LGTM! Tested in local.

**Comment by eantones** [comment]
Please squash, thanks!

**Pull request merged**
