### PR TITLE
[14.0][MIG] account_asset_active

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@eantones this one is ready

**Review by ChrisOForgeFlow — APPROVED** [review]
Functional and Code Review Ok

**Review by eantones — CHANGES_REQUESTED** [review]
@ChrisOForgeFlow please squash new commits into the one with title "Migration 14.0"

**Comment by ChrisOForgeFlow** [comment]
> @ChrisOForgeFlow please squash new commits into the one with title "Migration 14.0"

Done, but last commit is necessary to resolve merge conflict

**Comment by eantones** [comment]
> > @ChrisOForgeFlow please squash new commits into the one with title "Migration 14.0"
> 
> Done, but last commit is necessary to resolve merge conflict

You don't really need that commit, the branch is yours and you should be able to squash or remove the commit and force push it. Try a interactive rebase and fixup the last commit

**Comment by ChrisOForgeFlow** [comment]
> > > @ChrisOForgeFlow please squash new commits into the one with title "Migration 14.0"
> > 
> > 
> > Done, but last commit is necessary to resolve merge conflict
> 
> You don't really need that commit, the branch is yours and you should be able to squash or remove the commit and force push it. Try a interactive rebase and fixup the last commit

You're right, I correct branch

**Comment by LoisRForgeFlow** [comment]
Dependency to account-financial-tools needs to be added in the oca_dependencies.txt. (See travis error https://app.travis-ci.com/github/nuobit/odoo-addons/jobs/553440030#L1319)

**Comment by eantones** [comment]
@ChrisOForgeFlow this is already in Odoo core, it was not necessary to migrate to 14.0...I'm closing this PR

**Pull request closed without merging**
