### PR TITLE
[14.0][MIG] stock_picking_partner_ref

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
> Hi @MiquelRForgeFlow why are you removing these lines from all files? Is some new OCA guideline?

Not from all files, only from init files. See https://github.com/OCA/maintainer-tools/pull/260.

> @MiquelRForgeFlow Why did you change the expression? In that case I don't want to do a search for element, in this case I know that the field I'm looking for is right below the root element. Why force a search here?

Yeah, you are right, this is a search view so is not needed the `//`. I can revert it.

**Comment by eantones** [comment]
> > Hi @MiquelRForgeFlow why are you removing these lines from all files? Is some new OCA guideline?
> 
> Not from all files, only from init files. See [OCA/maintainer-tools#260](https://github.com/OCA/maintainer-tools/pull/260).
> > Correct, just the init files
>
> > @MiquelRForgeFlow Why did you change the expression? In that case I don't want to do a search for element, in this case I know that the field I'm looking for is right below the root element. Why force a search here?
> 
> Yeah, you are right, this is a search view so is not needed the `//`. I can revert it.
> > OK

**Comment by MiquelRForgeFlow** [comment]
@eantones this one is ready

**Review by mariadforgeflow — APPROVED** [review]
LGTM. Tested functionally.

**Pull request merged**
