### PR TITLE
[14.0][ADD] rma_repair_employee

### PR DESCRIPTION
**Pull request by FrankC013**

### CODE REVIEW

**Review by eantones — APPROVED** [review]

**Comment by FrankC013** [comment]
I have reverted the PR to its original state. I have another proposal stashed and pending for discussion.

**Review by eantones — CHANGES_REQUESTED** [review]
Use user_id instead of employee_id

**Comment by FrankC013** [comment]
@eantones Pending to close. New approach #400

**Comment by eantones** [comment]
Superseded by #400

**Pull request closed without merging**
