### PR TITLE
[14.0][MIG] base_report_pdf_css_reset

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@eantones this one is ready

**Review by ChrisOForgeFlow — APPROVED** [review]
Functional Review related to #25 
Code Review Ok

**Comment by eantones** [comment]
@ChrisOForgeFlow did you check if this patch is still necessary in 14.0?

**Comment by ChrisOForgeFlow** [comment]
> @ChrisOForgeFlow did you check if this patch is still necessary in 14.0?

Is only valid for report on #25, but I test and check that code works on this context

Maybe we can try something with this variable full_width, calling  web.basic_layout or web.minimal_layout on report, what do you think?

https://github.com/odoo/odoo/blob/1de3a4bee7b1df4960694d0851e72ef2eecb98a9/addons/web/views/report_templates.xml#L27
https://github.com/odoo/odoo/blob/1de3a4bee7b1df4960694d0851e72ef2eecb98a9/addons/web/views/report_templates.xml#L27
https://github.com/odoo/odoo/blob/1de3a4bee7b1df4960694d0851e72ef2eecb98a9/addons/web/views/report_templates.xml#L285

**Comment by eantones** [comment]
The web.minimal_layout has 'container' hard-coded so we cannot use it but the full_width is something new in 14.0 and we can try to refactor the module using it after the migration

**Pull request merged**
