### PR TITLE
[14.0][UPD] copier-answers: bump version and add ci

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Oversight of https://github.com/nuobit/odoo-addons/pull/79.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@eantones please, merge this leftover :)

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Copier does not work this way, you should use copier update and answer the questions, that would trigger more changes. Changing the copier-answers file manually does not make any sense. (you have a clean comment in the first line of the file :wink: )

**Comment by MiquelRForgeFlow** [comment]
> use copier update and answer the questions, that would trigger more changes

done

**Comment by eantones** [comment]
@LoisRForgeFlow is it ok now?

**Comment by LoisRForgeFlow** [comment]
This seems to me very few changes for +0.2 versions of the template, plus, anyway the change proposed here won't make any difference in the current CIs (only added the stale job). 

Not a blocking comment, you can merge, it won't hurt.

**Comment by eantones** [comment]
ok @LoisRForgeFlow thanks!

**Comment by MiquelRForgeFlow** [comment]
> This seems to me very few changes for +0.2 versions of the template

That's because I added manually many of the changes in the previous PR haha

**Pull request merged**
