### PR TITLE
[14.0][MIG] stock_orderpoint_manual_procurement_zero: Migration to 14.0

### PR DESCRIPTION
**Pull request by ChrisOForgeFlow**
Standard Migration

### CODE REVIEW

**Comment by eantones** [comment]
@ChrisOForgeFlow the commit should be splited here as well to avoid conflicts

**Comment by ChrisOForgeFlow** [comment]
> @ChrisOForgeFlow the commit should be splited here as well to avoid conflicts

Done

**Comment by eantones** [comment]
Thanks @ChrisOForgeFlow :-)

**Review by mariadforgeflow — APPROVED** [review]
Tested!

**Comment by eantones** [comment]
@ChrisOForgeFlow there's conflicts, please rebase, thanks

**Comment by ChrisOForgeFlow** [comment]
> @ChrisOForgeFlow there's conflicts, please rebase, thanks

Done

**Pull request merged**
