### PR TITLE
[14.0][MIG] account_cash_statement_restrict

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@eantones this one is ready

**Review by ChrisOForgeFlow — APPROVED** [review]
Functional and Code Review

**Review by eantones — CHANGES_REQUESTED** [review]
@ChrisOForgeFlow please squash new commits into the one with title "Migration 14.0"

**Comment by ChrisOForgeFlow** [comment]
> @ChrisOForgeFlow please squash new commits into the one with title "Migration 14.0"

Done!

**Pull request merged**
