### PR TITLE
[14.0][MIG] l10n_es_aeat_vat_special_prorrate

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
rebased to fix conflict in oca_dependencies.

**Comment by MiquelRForgeFlow** [comment]
@eantones this one is ready

**Review by ChrisOForgeFlow — APPROVED** [review]
Code Review Ok
Functional Review related to #123

**Comment by LoisRForgeFlow** [comment]
@eantones could you push the current status of this? so @etobella can have a look at the implementation?

**Comment by eantones** [comment]
@LoisRForgeFlow the branch is not yet pushable, there's still some things to put together.

**Comment by etobella** [comment]
@eantones Just one question, I was checking an idea following the usage of groups of taxes as you stated, but I lost the base of the taxes. So, there was wrong information on VAT Book and 303 Tax Report. Did you notice the same problems?

**Comment by eantones** [comment]
Superseded by #154

**Pull request closed without merging**
